### ISSUE TITLE
Page not found gets cached

### ISSUE THREAD

**Issue by RobinHoutevelts** [wieni/wmcontroller#21] opened 2017-02-16 16:08 UTC
When logged in I can visit
https://eoswetenschap.wieni.work/natuur-milieu/natuur-om-de-hoek

When incognito I get `De pagina die je zoekt bestaat niet meer.`

The http status code is `200`.

----

Steps to reproduce:
- Log in to eos
- Change an article title
    - The alias will change
- While incognito, visit the original alias
     - It'll say `De pagina die je zoekt bestaat niet meer.`
- Revert the title change
   - The alias will change back to the original.
- While incognito, visit the original alias 
    - **you'll still see the `De pagina die je zoekt bestaat niet meer.`**

Updating the entity does not resolve this issue.

**Comment by frizinak** [comment] 2017-02-16 17:06
Can't reproduce.

Are you triggering a 404 from your bundle specific controller?

I'm guessing:
- entity found: max-age: 123
- trigger bundle controller -> 404
- cache page without any tags (none were dispatched, cause none were rendered)

To fix:
- ignore non 2xx responses (more cache misses and entity_loads) OR
- add cache tags for the main entity even if it wasn't rendered

If you can confirm the 404 is triggered from a controller and not higher up, we can be pretty sure this assumption is correct.

**Comment by frizinak** [comment] 2017-02-17 13:08
fixed in #56767b1d6d621c345fe267cbc776385d023b7d60

for future reference: this bug can be reproduced by both path regexes and notFoundExceptions in bundle controllers, so ignoring 404's seems the only option.

**Closed by frizinak** 2017-02-17 13:08 UTC
